<?php

/**
 * @file
 * Contains starwars.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function starwars_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the starwars module.
    case 'help.page.starwars':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module Star Wars') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function starwars_theme() {
  return [
    'starwars' => [
      'render element' => 'children',
    ],
  ];
}
